const productos = [
  {
    id: 1,
    tipo: "consulta",
    categoria: "clinica",
    img: "./src/img/consultaMedica.jpg",
    nombre: "Consulta Clinica",
    cantidad: 1,
    precio: "$1000 - $1500",
  },
  {
    id: 2,
    tipo: "consulta",
    categoria: "cardiologia",
    img: "./src/img/consultaMedica.jpg",
    nombre: "Consulta Cardiologia",
    cantidad: 1,
    precio: "$1000 - $1500",
  },
  {
    id: 3,
    tipo: "onsulta",
    categoria: "otorrino",
    img: "./src/img/consultaMedica.jpg",
    nombre: "Consulta Otorrino",
    cantidad: 1,
    precio: "$1000 - $1500",
  },
  {
    id: 4,
    tipo: "consulta",
    categoria: "neurologia",
    img: "./src/img/consultaMedica.jpg",
    nombre: "Consulta Neurologia",
    cantidad: 1,
    precio: "$1000 - $1500",
  },
  {
    id: 5,
    tipo: "consulta",
    categoria: "oftalmologia",
    img: "./src/img/consultaMedica.jpg",
    nombre: "Consulta Oftalmologia",
    cantidad: 1,
    precio: "$1000 - $1500",
  },
  {
    id: 6,
    tipo: "imagenes",
    categoria: "resonancia",
    img: "./src/img/resonancia.jpg",
    nombre: "Resonancia de Hombros",
    cantidad: 1,
    precio: "$1000 - $1500",
  },
  {
    id: 7,
    tipo: "imagenes",
    categoria: "resonancia",
    img: "./src/img/resonancia.jpg",
    nombre: "Resonancia de Cadera",
    cantidad: 1,
    precio: "$1000 - $1500",
  },
  {
    id: 8,
    tipo: "imagenes",
    categoria: "resonancia",
    img: "./src/img/resonancia.jpg",
    nombre: "Resonancia de Manos",
    cantidad: 1,
    precio: "$1000 - $1500",
  },
  {
    id: 9,
    tipo: "imagenes",
    categoria: "resonancia",
    img: "./src/img/resonancia.jpg",
    nombre: "Resonancia de Rodilla",
    cantidad: 1,
    precio: "$1000 - $1500",
  },
  {
    id: 10,
    tipo: "imagenes",
    categoria: "resonancia",
    img: "./src/img/resonancia.jpg",
    nombre: "Resonancia de Pie",
    cantidad: 1,
    precio: "$1000 - $1500",
  },
  {
    id: 11,
    tipo: "imagenes",
    categoria: "ecografia",
    img: "./src/img/doppler.jpg",
    nombre: "Ecografia de Partes Blandas",
    cantidad: 1,
    precio: "$1000 - $1500",
  },
  {
    id: 12,
    tipo: "imagenes",
    categoria: "doppler",
    img: "./src/img/doppler.jpg",
    nombre: "Ecografia de Abdomen",
    cantidad: 1,
    precio: "$1000 - $1500",
  },
  {
    id: 13,
    tipo: "imagenes",
    categoria: "radiografia",
    img: "./src/img/radiografias.jpg",
    nombre: "Radiografias",
    cantidad: 1,
    precio: "$1000 - $1500",
  },
  {
    id: 14,
    tipo: "imagenes",
    categoria: "doppler",
    img: "./src/img/doppler.jpg",
    nombre: "Ecodopler Color",
    cantidad: 1,
    precio: "$1000 - $1500",
  },
  {
    id: 15,
    tipo: "laboratorio",
    categoria: "laboratorio",
    img: "./src/img/laboratorio.jpg",
    nombre: "Estudios de Rutina (hasta 10)",
    cantidad: 1,
    precio: "$1000 - $1500",
  },
  {
    id: 16,
    tipo: "laboratorio",
    categoria: "laboratorio",
    img: "./src/img/laboratorio.jpg",
    nombre: "Vitamina D",
    cantidad: 1,
    precio: "$1000 - $1500",
  },
  {
    id: 17,
    tipo: "sesiones",
    categoria: "sesionesFkt",
    img: "./src/img/fkt.jpg",
    nombre: "Fisiokinesioterapia",
    cantidad: 1,
    precio: "$1000 - $1500",
  },
  {
    id: 18,
    tipo: "sesiones",
    categoria: "sesionesPsico",
    img: "./src/img/sesionPsico.jpg",
    nombre: "Psicología",
    cantidad: 1,
    precio: "$1000 - $1500",
  },
  {
    id: 19,
    tipo: "laboratorio",
    categoria: "laboratorio",
    img: "./src/img/laboratorio.jpg",
    nombre: "Estudios de Rutina (hasta 30)",
    cantidad: 1,
    precio: "$3000 - $4500",
  },
];

export const gFetch = new Promise((res, rej) => {
  let condition = true;
  setTimeout(() => {
    if (condition) {
      res(productos);
    } else {
      rej("Error");
    }
  }, 3000);
});
